quotes = [
    "Success is built on daily effort and resilience.",
    "Every failure is a lesson that brings you closer to success.",
    "Persistence turns dreams into reality.",
    "The most successful people never give up when faced with obstacles.",
    "Small, consistent actions lead to big achievements.",
    "Success is not about luck—it's about discipline.",
    "Hard work beats talent when talent doesn't work hard.",
    "The road to success is paved with patience and effort.",
    "Winners keep going when others quit.",
    "Success comes to those who refuse to stop trying.",
    "Every expert was once a beginner who never gave up.",
    "Consistency is the key to long-term success.",
    "Success is a journey, not a destination.",
    "The difference between ordinary and extraordinary is persistence.",
    "Challenges are opportunities to grow stronger.",
    "Success requires sacrifice and dedication.",
    "Keep pushing forward, even when progress seems slow.",
    "The only way to fail is to stop trying.",
    "Success is the sum of small efforts repeated daily.",
    "Believe in yourself, and success will follow.",
    "Learning is the foundation of all achievement.",
    "The more you learn, the more opportunities you create.",
    "Knowledge is power—never stop acquiring it.",
    "Growth happens outside your comfort zone.",
    "Every skill you learn increases your value.",
    "Curiosity fuels lifelong learning.",
    "The best investment you can make is in yourself.",
    "Learning from mistakes makes you wiser.",
    "Stay humble—there's always more to learn.",
    "Adaptability comes from continuous learning.",
    "The mind is like a muscle—it grows with use.",
    "Education doesn't end with school; it's a lifelong process.",
    "The most successful people are always students.",
    "Learning keeps your mind sharp and agile.",
    "Knowledge opens doors that money cannot.",
    "The more you know, the more confident you become.",
    "Never stop asking questions—it's how you grow.",
    "Learning from others accelerates your progress.",
    "Self-improvement is the best form of investment.",
    "A learning mindset leads to endless possibilities.",
    "Reading is the gateway to new worlds.",
    "Books are the quietest yet most powerful teachers.",
    "The more you read, the more perspectives you gain.",
    "Reading strengthens focus and concentration.",
    "A book a day keeps ignorance away.",
    "Knowledge gained from reading is never wasted.",
    "Reading enhances creativity and problem-solving.",
    "Books provide wisdom without the need for personal mistakes.",
    "Reading is exercise for the brain.",
    "The best leaders are avid readers.",
    "A well-read person is never bored.",
    "Reading improves vocabulary and communication skills.",
    "Books allow you to learn from history's greatest minds.",
    "Reading reduces stress and expands thinking.",
    "The habit of reading separates achievers from dreamers.",
    "Knowledge from books gives you an edge in life.",
    "Reading is the best way to travel without moving.",
    "A library is a treasure chest for the mind.",
    "The more you read, the better you write and speak.",
    "Reading is the foundation of self-education.",
    "Time is your most valuable asset—use it wisely.",
    "Proper planning prevents poor performance.",
    "Prioritize tasks to maximize efficiency.",
    "Procrastination is the thief of time.",
    "Discipline is choosing what you want most over what you want now.",
    "A well-organized day leads to success.",
    "Multitasking reduces quality—focus on one thing at a time.",
    "Set deadlines to stay accountable.",
    "Time wasted can never be regained.",
    "The early bird gets the worm—start your day strong.",
    "Break big tasks into smaller, manageable steps.",
    "Eliminate distractions to boost productivity.",
    "Saying 'no' to unimportant tasks saves time for what matters.",
    "Track your time to identify inefficiencies.",
    "Balance work and rest to avoid burnout.",
    "A schedule brings structure to success.",
    "Time management reduces stress and increases freedom.",
    "Productivity comes from intentional action.",
    "The most successful people guard their time fiercely.",
    "Use tools like calendars and to-do lists to stay on track.",
    "Clear communication prevents misunderstandings.",
    "Listening is just as important as speaking.",
    "Words have power—use them wisely.",
    "Good communication builds strong relationships.",
    "Speak with confidence and clarity.",
    "Nonverbal cues often speak louder than words.",
    "Effective leaders are great communicators.",
    "Tailor your message to your audience.",
    "Honesty strengthens trust in communication.",
    "Ask questions to ensure understanding.",
    "Public speaking skills open doors to opportunities.",
    "A well-delivered message can inspire action.",
    "Communication is the bridge between confusion and clarity.",
    "Respectful dialogue leads to better solutions.",
    "Active listening improves relationships.",
    "Miscommunication is the root of many conflicts.",
    "Great communicators make complex ideas simple.",
    "Body language can reinforce or contradict your words.",
    "Persuasive communication drives success.",
    "Practice empathy to connect deeply with others.",
    "Small steps lead to big changes over time.",
    "Consistency beats intensity in the long run.",
    "Daily habits shape your future.",
    "Improvement of just 1% daily leads to massive growth.",
    "Patience is key—real progress takes time.",
    "Focus on progress, not perfection.",
    "Tiny actions compound into extraordinary results.",
    "Discipline today creates freedom tomorrow.",
    "Success is the result of daily choices.",
    "Track your progress to stay motivated.",
    "Small wins build confidence and momentum.",
    "The journey of a thousand miles begins with one step.",
    "Don't underestimate the power of incremental growth.",
    "Habits, not miracles, create lasting success.",
    "Every day is an opportunity to improve.",
    "Little by little, a little becomes a lot.",
    "Sustainable growth comes from steady effort.",
    "Focus on the process, and the results will follow.",
    "Small positive changes accumulate into transformation.",
    "The secret to success is showing up every day.",
    "Your mindset determines your success.",
    "A positive attitude attracts positive outcomes.",
    "Challenges are opportunities in disguise.",
    "Belief in yourself is the first step to achievement.",
    "Motivation gets you started—discipline keeps you going.",
    "Failure is feedback, not defeat.",
    "Growth begins at the edge of your comfort zone.",
    "What you think, you become.",
    "Optimism fuels perseverance.",
    "Self-doubt kills more dreams than failure ever will.",
    "Focus on solutions, not problems.",
    "Gratitude increases happiness and motivation.",
    "Your thoughts shape your reality.",
    "Resilience turns setbacks into comebacks.",
    "The only limits are the ones you set for yourself.",
    "Success starts with self-belief.",
    "A strong mindset overcomes any obstacle.",
    "Progress requires embracing discomfort.",
    "Every struggle is a stepping stone to success.",
    "Mindset is the foundation of achievement.",
    "Discipline is the bridge between goals and success.",
    "Hard work never goes out of style.",
    "Excellence is a habit, not an act.",
    "Success favors those who put in the effort.",
    "Laziness may feel good now, but regret lasts longer.",
    "Discipline creates freedom in the long run.",
    "Work ethic outshines talent over time.",
    "Consistency is the hallmark of champions.",
    "Effort is the price of achievement.",
    "The grind today leads to greatness tomorrow.",
    "No shortcuts exist to lasting success.",
    "Discipline turns dreams into reality.",
    "Success is earned, not given.",
    "The harder you work, the luckier you get.",
    "Excellence comes from repetition and refinement.",
    "Small daily disciplines lead to big results.",
    "Success is about doing what others won't.",
    "Discipline is choosing what you want most over what you want now.",
    "Work in silence; let success make the noise.",
    "The secret to success is hidden in your daily routine.",
    "Leaders inspire action through example.",
    "True leadership is service, not control.",
    "Influence is built on trust and respect.",
    "Great leaders empower others to succeed.",
    "Vision separates leaders from followers.",
    "Leadership is about making others better.",
    "Humility strengthens leadership.",
    "Decisions define leaders.",
    "A leader's attitude sets the team's culture.",
    "Accountability is the mark of true leadership.",
    "Leaders communicate with clarity and purpose.",
    "Integrity is the foundation of leadership.",
    "The best leaders are lifelong learners.",
    "Leadership requires courage and conviction.",
    "Empathy makes leaders relatable and effective.",
    "Leaders focus on solutions, not blame.",
    "Strong leaders create more leaders.",
    "Vision without execution is just a dream.",
    "Leadership is action, not position.",
    "The greatest leaders lead by serving.",
    "Success is a combination of preparation and opportunity.",
    "The only way to predict the future is to create it.",
    "Success is not about being the best but becoming your best.",
    "Your habits today define your success tomorrow.",
    "Dream big, start small, act now.",
    "Success is not final; failure is not fatal—keep going.",
    "The only thing standing between you and success is persistence.",
    "Every master was once a disaster—keep improving.",
    "Success is the result of relentless effort.",
    "The path to success is always under construction.",
    "Success is not about having everything but making the best of what you have.",
    "Your attitude determines your altitude in life.",
    "The difference between who you are and who you want to be is action.",
    "Success is not just about reaching goals but enjoying the journey.",
    "The greatest risk is not taking one.",
    "Success begins the moment you decide to pursue it.",
    "You don't have to be perfect—just keep making progress.",
    "The only failure is not trying.",
    "Success is a choice, not a chance.",
    "Keep moving forward—your best is yet to come."
]